---
title: "Final Analysis - Cluster Study"
author: "Matthew Fikes"
date: "July 14, 2021"
output: pdf_document
---
### import data
```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(factoextra)
library(cluster)
library(ggpubr)
library(dbscan)
library(fpc)
library(clustertend)
set.seed(42)
df <- read_csv('C:/Users/mfikes/Documents/Bellevue/DSC630/data_model.csv')
```

### remove matriculated students from set
```{r}

nonmatric <- df[ which(df$target=='0'), ] #subset for non-matriculated students
matric <- df[ which(df$target=='1'), ] #subset for matriculated students

cluster_df = nonmatric[, colSums(nonmatric != 0) > 0]
cluster_df <- subset (cluster_df,select = c(-Age,-Num_Dual_Terms))


```


## Find optimal value for k

```{r find k values}
rng<-2:20 #K from 2 to 10
tries <-10 #Run the K Means algorithm 20 times
avg.totw.ss <-integer(length(rng)) #Set up an empty vector to hold all of points
for(v in rng){ # For each value of the range variable
 v.totw.ss <-integer(tries) #Set up an empty vector to hold the 100 tries
 for(i in 1:tries){
 k.temp <-kmeans(cluster_df,centers=v) #Run kmeans
 v.totw.ss[i] <-k.temp$tot.withinss#Store the total withinss
 }
 avg.totw.ss[v-1] <-mean(v.totw.ss) #Average the 100 total withinss
}
plot(rng,avg.totw.ss,type="b", main="Total Within SS by Various K",
 ylab="Average Total Within Sum of Squares",
 xlab="Value of K")

```


```{r}
# plot to find best epsilon distance value (eps) for DBSCAN
# source: https://www.datanovia.com/en/lessons/dbscan-density-based-clustering-essentials/

dbscan::kNNdistplot(cluster_df, k =  5)
abline(h = .2, lty = 2)

```



```{r fig.height=10}
# get DBSCAN clusters
db <- fpc::dbscan(cluster_df, eps = .2, MinPts = 4)
# Plot DBSCAN results
fviz_cluster(db, cluster_df, stand = FALSE, ellipse.type='convex', geom = "point",show.clust.cent=FALSE,outlier.pointsize=.05,shape=1,outlier.color='black',outlier.shape=0) + theme(legend.position = "none")

```


### check hopkins score
```{r}
hopkins(cluster_df, 10, byrow = F, header = F)
```
### PAM clustering
```{r}
# set up range of K values to test
rng <- 5:10
# test all values in range and plot
for (i in rng){
  
  km <- pam(cluster_df,i,nstart=2,stand=TRUE,metric='euclidean')
  print(fviz_cluster(km, data = cluster_df,geom='point',ellipse.type='convex'))
}
```

```{r}
#export the cluster data
cluster_df$cluster <- km$cluster

outlier_cluster <- cluster_df %>% filter(cluster==5)

cluster_df$x = res.pca$x
write.csv(cluster_df,"clusters.csv", row.names = FALSE)

```

